
float32 rpm 
float32 force
int32 passes
float32 tcp_speed
float32 contact_time
---
bool success
string message

# Contains a copy of the request settings
data_gathering_msgs/GrindSettings grind_settings